
set shell=/bin/bash " optional for Vundle
set nocompatible              " be iMproved, required
filetype off                  " required

" setting
let g:vspath = "~/projects/vim-studio"
let g:python3 = "/usr/local/bin/python3"
let g:ycm = 0

" init
exec "source " . g:vspath . "/config/common.vim"

" TODO: 代码格式化, ALE, YCM代码提示没有参数 ...
